version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    container_name: sidekiq
    build: .
    command: bundle install && bundle exec sidekiq
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  rails:
    container_name: rails
    build: .
    command: bundle exec rails server -b '0.0.0.0'
    ports:
      - "30123:3000"
    depends_on:
      - sidekiq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=${RAILS_ENV:-development}
