version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - redis

  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
