version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis

  rails:
    build: .
    command: bundle exec rails server -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "30123:3000"
    depends_on:
      - sidekiq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=${RAILS_ENV:-development}
