source 'https://rubygems.org'
gem 'binding_of_caller'
gem 'bootstrap-will_paginate'
gem 'bootstrap_form'
gem 'bullet'
gem 'coffee-rails'
gem 'devise'
gem 'devise_invitable'
gem 'diffy'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'faker'
gem 'flamegraph'
gem 'icalendar'
gem 'jquery-rails'
gem 'loaf'
gem 'lockbox'
gem 'memory_profiler'
gem 'minidusen'
gem 'mysql2'
gem 'net-http-persistent'
gem 'nprogress-rails'
gem 'paperclip'
gem 'paper_trail'
gem 'paranoia'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-mini-profiler'
gem 'rails'
gem 'rails-i18n'
gem 'rails-ujs'
gem 'rb-readline'
gem 'redcarpet'
gem 'rqrcode_png'
gem 'sass-rails'
gem "secure_headers", "~> 6.3"
gem 'sprockets'
gem 'stackprof'
gem 'switch_user'
gem 'therubyracer'
gem 'turbolinks'
gem 'tzinfo'
gem 'uglifier'
gem 'web-console'
gem "webpacker"
gem 'whenever', require: false
gem 'will_paginate'
gem 'wine_bouncer'
group :doc do
  gem 'sdoc', require: false
end
