source 'https://rubygems.org'
gem 'apipie-rails'
gem 'better_errors'
gem 'binding_of_caller'
gem 'bootstrap-will_paginate'
gem 'bootstrap_form'
gem 'bullet'
gem 'chartkick'
gem 'cloudinary'
gem 'coffee-rails'
gem 'devise'
gem 'devise_invitable'
gem 'diffy'
gem 'documentation'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'faker'
gem 'flamegraph'
gem 'font_awesome5_rails'
gem 'groupdate'
gem 'icalendar'
gem 'incoming'
gem 'jbuilder'
gem 'jquery-rails'
gem 'loaf'
gem 'memory_profiler'
gem 'minidusen'
gem 'mysql2'
gem 'net-http-persistent'
gem 'nprogress-rails'
gem 'paper_trail'
gem 'paperclip'
gem 'paranoia'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-mini-profiler'
gem 'rails', '~>6'
gem 'rails-controller-testing'
gem 'rails-i18n'
gem 'rb-readline'
gem 'redcarpet'
gem 'rqrcode_png'
gem 'sass-rails'
gem "sassc", "< 2.1.0"
gem 'sprockets', '~> 3.7.2'
gem 'stackprof'
gem 'switch_user'
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'tzinfo'
gem 'uglifier'
gem 'web-console'
gem "webpacker"
gem 'whenever', require: false
gem 'will_paginate'
gem 'wine_bouncer'
group :doc do
  gem 'sdoc', require: false
end
