source 'https://rubygems.org'
gem 'google_drive'
gem 'acme_plugin'
gem 'ahoy_matey'
gem 'better_errors'
gem 'binding_of_caller'
gem 'bootstrap-will_paginate'
gem 'bootstrap_form'
gem 'bullet'
gem 'capistrano-rpush'
gem 'chartkick'
gem 'cloudinary'
gem 'coffee-rails'
gem 'devise', git: 'https://github.com/plataformatec/devise'
gem 'devise_invitable'
gem 'diffy'
gem 'documentation'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'faker'
gem 'flamegraph'
gem 'font_awesome5_rails'
gem 'grape'
gem 'grape-swagger'
gem 'groupdate'
gem 'icalendar'
gem 'incoming'
gem 'jbuilder'
gem 'jquery-rails'
gem 'loaf' 
gem 'memory_profiler'
gem 'minidusen'
gem 'mysql2'
gem 'net-http-persistent'
gem 'nprogress-rails'
gem 'paper_trail'
gem 'paperclip'
gem 'paranoia'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-mini-profiler'
gem 'rails'
gem 'rails-controller-testing'
gem 'rails-i18n'
gem 'rb-readline'
gem 'redcarpet'
gem 'rpush'
gem 'rqrcode_png'
gem 'sass-rails'
gem 'stackprof'
gem 'swagger-ui_rails'
gem 'swagger_ui_engine'
gem 'switch_user'
gem 'therubyracer'
gem 'trix', git: 'https://github.com/bcoia/trix'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'tzinfo'
gem 'uglifier'
gem 'web-console'
gem 'whenever', require: false
gem 'will_paginate'
gem 'wine_bouncer'
group :doc do
  gem 'sdoc', require: false
end
gem 'apipie-rails'
gem 'capistrano', group: :development
gem 'capistrano-rails', '~> 1.1'
gem 'rvm-capistrano'
