name: Brakeman

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.2']
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run brakeman
        continue-on-error: true
        run: bundle exec brakeman
