name: Tests

on: [push, pull_request]

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2', '2.7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Start database server
        run: sudo systemctl start mysql
      - name: Setup database connection configuration
        run: cp config/database-ci.yml config/database.yml
      - name: Setup database
        run: bundle exec rails db:setup
      - name: Yarn install
        run: yarn install --check-files
      - name: Procompile assets
        run: bundle exec rails assets:precompile
      - name: Run tests
        run: bundle exec rails test
