name: Tests

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - "*"

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1.6"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: "yarn"

      - name: Set up database
        run: bundle exec rails db:setup

      - name: Procompile assets
        run: bundle exec rails assets:precompile NODE_OPTIONS="--openssl-legacy-provider"

      - name: Run tests
        run: bundle exec rails test:all

  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1.6"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RuboCop
        continue-on-error: true
        run: bundle exec rubocop --parallel

  brakeman:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1.6"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run brakeman
        continue-on-error: true
        run: bundle exec brakeman
