name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2', '2.7.4']
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_HOST: 127.0.0.1
          MARIADB_DB: hamers_test
          MARIADB_USER: hamers
          MARIADB_PASSWORD: hamers
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports: [3306]
    steps:
    - uses: actions/checkout@v2
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: |
        sudo service mysql start
        bundle exec rake
